'use client';
import React, { useEffect, useState } from 'react';
import Link from 'next/link';
import { supabase } from '../supabaseClient';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [user, setUser] = useState<any>(null);
  const [role, setRole] = useState<string | null>(null);

  useEffect(() => {
    supabase.auth.getUser().then(async ({ data }) => {
      setUser(data.user);
      if (data.user) {
        const { data: profile } = await supabase.from('profiles').select('role').eq('id', data.user.id).single();
        setRole(profile?.role || null);
      } else {
        setRole(null);
      }
    });
    const { data: listener } = supabase.auth.onAuthStateChange(async (_event, session) => {
      setUser(session?.user ?? null);
      if (session?.user) {
        const { data: profile } = await supabase.from('profiles').select('role').eq('id', session.user.id).single();
        setRole(profile?.role || null);
      } else {
        setRole(null);
      }
    });
    return () => {
      listener.subscription.unsubscribe();
    };
  }, []);

  const handleLogout = async () => {
    await supabase.auth.signOut();
    window.location.href = '/';
  };

  return (
    <html lang="en">
      <body style={{ margin: 0, fontFamily: 'sans-serif', background: '#f9f9f9' }}>
        <nav style={{ display: 'flex', gap: 24, alignItems: 'center', padding: '16px 32px', background: '#fff', borderBottom: '1px solid #eee', marginBottom: 32 }}>
          <Link href="/" style={{ fontWeight: 'bold', color: '#0070f3', fontSize: 20, textDecoration: 'none' }}>Slick Laids</Link>
          <Link href="/dashboard" style={{ color: '#333', textDecoration: 'none' }}>Dashboard</Link>
          <Link href="/profile" style={{ color: '#333', textDecoration: 'none' }}>Profile</Link>
          <Link href="/shares" style={{ color: '#333', textDecoration: 'none' }}>Shares</Link>
          <Link href="/penalties" style={{ color: '#333', textDecoration: 'none' }}>Penalties</Link>
          <Link href="/jamii" style={{ color: '#333', textDecoration: 'none' }}>Jamii</Link>
          <Link href="/loans" style={{ color: '#333', textDecoration: 'none' }}>Loans</Link>
          <Link href="/repayments" style={{ color: '#333', textDecoration: 'none' }}>Repayments</Link>
          {role === 'chairperson' || role === 'secretary' ? (
            <Link href="/admin/users" style={{ color: '#333', textDecoration: 'none' }}>Admin Users</Link>
          ) : null}
          {user ? (
            <button onClick={handleLogout} style={{ marginLeft: 'auto', background: '#0070f3', color: '#fff', border: 'none', borderRadius: 4, padding: '8px 16px', cursor: 'pointer' }}>Logout</button>
          ) : (
            <Link href="/auth" style={{ marginLeft: 'auto', background: '#0070f3', color: '#fff', border: 'none', borderRadius: 4, padding: '8px 16px', textDecoration: 'none' }}>Login / Sign Up</Link>
          )}
        </nav>
        <div>{children}</div>
      </body>
    </html>
  )
}
